server:
  port: 7000
spring:
  application:
    name: ${DDSTREAM_SERVER_APPLICATION_NAME:DDStream-server}
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        auto-ip-address: true
        fail-fast: false
  datasource:
    driver-class-name: org.h2.Driver
    username: ${DDSTREAM_CLIENT_DATABASE_USERNAME:sa}
    url: jdbc:h2:./database/test
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      mode: always
      data-locations: classpath:sql/init.sql
management:
  endpoints:
    web:
      exposure:
        include: metrics,health
    endpoint:
      health:
        show-details: always
dd-stream:
  client:
    application:
      name: ${DDSTREAM_CLIENT_APPLICATION_NAME:DDStream-client}